site_name: Sito Bank

theme:
  name: material
  features:
    - content.full-width

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - js/mermaid-init.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css





