name: Deploy MkDocs using gh-deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write   # ← CLAVE
  pages: none
  id-token: none

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ← MUY IMPORTANTE

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Debug files
        run: |
          pwd
          ls -la


      - name: Deploy with MkDocs gh-deploy
        run: mkdocs gh-deploy --force
